package org.example.backend.enums;

public enum NotificationType {
    FRIEND_REQUEST_RECEIVED,
    FRIEND_REQUEST_ACCEPTED,
    POST_REACTED,
    POST_COMMENTED,
    COMMENT_REPLIED,
    GROUP_JOIN_REQUEST_RECEIVED,
    GROUP_JOIN_REQUEST_ACCEPTED,
    GROUP_JOIN_REQUEST_REJECTED
}
